In [8]:
import pandas as pd
import seaborn as sns
import numpy as np

In [9]:
df_count = pd.read_csv('../data/raw/Traffic_Volume_Counts__2014-2019_.csv', delimiter=',')

In [10]:
df_count.head(20)

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,...,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,2,70376,3 Avenue,East 154 Street,East 155 Street,NB,09/13/2014,204.0,177.0,133.0,...,520,611,573,546,582,528,432,328,282,240
1,2,70376,3 Avenue,East 155 Street,East 154 Street,SB,09/13/2014,140.0,51.0,128.0,...,379,376,329,362,418,335,282,247,237,191
2,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,EB,09/13/2014,94.0,73.0,65.0,...,280,272,264,236,213,190,199,183,147,103
3,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,WB,09/13/2014,88.0,82.0,75.0,...,237,276,223,240,217,198,186,162,157,103
4,62,147673,Broadway,West 242 Street,240 Street,SB,09/13/2014,255.0,209.0,149.0,...,732,809,707,675,641,556,546,465,425,324
5,62,158447,Broadway,West 242 Street,240 Street,NB,09/13/2014,255.0,209.0,149.0,...,732,809,707,675,641,556,546,465,425,324
6,62,255653,Broadway,West 242 Street,240 Street,SB,09/13/2014,87.0,86.0,78.0,...,200,200,209,175,181,167,144,129,112,103
7,71,139620,Bronx River Parkway,Bronx River,East Gun Hill Road,NB,09/13/2014,802.0,445.0,388.0,...,2933,2904,2699,2877,2947,2532,2193,1820,1677,1331
8,71,139618,Bronx River Parkway,East Gun Hill Road,Bronx River,SB,09/13/2014,618.0,345.0,309.0,...,2676,2848,2680,2581,2274,2054,1762,1534,1308,1107
9,76,70364,Brook Avenue,East 152 Street,East 153 Street,SB,09/13/2014,79.0,58.0,41.0,...,288,300,301,305,294,222,183,134,129,97
10,89,69780,East 138 Street,Canal Place,Rider Avenue,EB,09/13/2014,339.0,233.0,239.0,...,517,475,517,603,495,479,458,419,429,340
11,89,69780,East 138 Street,Rider Avenue,Canal Place,WB,09/13/2014,282.0,229.0,182.0,...,491,484,469,495,427,430,368,346,335,283
12,102,69979,Concourse Village West,East 156 Street,East 156 Street,NB,09/13/2014,101.0,67.0,50.0,...,189,170,210,187,191,207,190,148,137,102
13,104,9001519,Courtladt Avenue,East 153 Street,East 154 Street,NB,09/13/2014,97.0,72.0,36.0,...,183,238,233,204,219,218,176,119,119,91
14,108,276970,East 144 Street,A J Griffin Place,Grand Concourse,WB,09/13/2014,77.0,42.0,29.0,...,167,187,207,140,141,155,117,89,68,83
15,108,276970,East 144 Street,Grand Concourse,A J Griffin Place,EB,09/13/2014,81.0,49.0,55.0,...,223,221,230,211,195,214,146,123,97,94
16,109,173496,East 149 Street,A J Griffin Place,Grand Concourse,WB,09/13/2014,348.0,303.0,280.0,...,643,669,634,617,635,590,541,456,420,356
17,109,173496,East 149 Street,Grand Concourse,A J Griffin Place,EB,09/13/2014,454.0,365.0,344.0,...,782,843,839,821,775,815,732,603,592,484
18,111,69836,East 149 Street,Morris Avenue,Park Avenue,WB,09/13/2014,338.0,304.0,271.0,...,726,794,739,708,747,690,635,545,474,411
19,111,69836,East 149 Street,Park Avenue,Morris Avenue,EB,09/13/2014,333.0,238.0,209.0,...,610,625,599,605,576,510,516,431,394,357

In [11]:
import geopandas as gpd
import pyproj
file = open('../data/raw/LION.geojson')
geo_data = gpd.read_file(file)

In [12]:
geo_data.head()

,OBJECTID,Street,SAFStreetName,FeatureTyp,SegmentTyp,IncExFlag,RB_Layer,NonPed,TrafDir,TrafSrc,...,FromLeft,ToLeft,FromRight,ToRight,Join_ID,L_PD_Service_Area,R_PD_Service_Area,TRUCK_ROUTE_TYPE,Shape__Length,geometry
0,1,EAST 168 STREET,,0,U,,B,,T,DOT,...,599,699,596,716,2251001000000,,,,396.030947,"LINESTRING (-73.90347 40.83036, -73.90238 40.8..."
1,2,WEST 192 STREET,,0,U,,B,,A,DOT,...,58,98,63,99,2798401000000,,,,279.360514,"LINESTRING (-73.90120 40.86662, -73.90207 40.8..."
2,3,UNION AVENUE,,0,U,,B,,W,DOT,...,1017,1079,1016,1084,2728001000000,,,,618.327133,"LINESTRING (-73.90118 40.82440, -73.90051 40.8..."
3,4,UNION AVENUE,BEHAGEN PLAYGROUND COMFORT STA,0,U,,B,,W,DOT,...,0,0,0,0,21279502000000X,,,,618.327133,"LINESTRING (-73.90118 40.82440, -73.90051 40.8..."
4,5,UNION AVENUE,BEHAGEN PLAYGROUND FIELD NORTH,0,U,,B,,W,DOT,...,0,0,0,0,21279503000000X,,,,618.327133,"LINESTRING (-73.90118 40.82440, -73.90051 40.8..."

In [13]:
df_count['Segment ID'].dtype, geo_data['SegmentID'].dtype

(dtype('int64'), dtype('O'))

In [14]:
geo_data['SegmentID'] = geo_data['SegmentID'].astype(str).astype(int)

In [15]:
a = df_count['Segment ID'].unique()
max(a)

9017050

In [16]:
b = geo_data['SegmentID'].unique()
max(b)

9024311

In [17]:
df_mean = df_count.groupby(['Segment ID'])[[
 '12:00-1:00 AM',
 '1:00-2:00AM',
 '2:00-3:00AM',
 '3:00-4:00AM',
 '4:00-5:00AM',
 '5:00-6:00AM',
 '6:00-7:00AM',
 '7:00-8:00AM',
 '8:00-9:00AM',
 '9:00-10:00AM',
 '10:00-11:00AM',
 '11:00-12:00PM',
 '12:00-1:00PM',
 '1:00-2:00PM',
 '2:00-3:00PM',
 '3:00-4:00PM',
 '4:00-5:00PM',
 '5:00-6:00PM',
 '6:00-7:00PM',
 '7:00-8:00PM',
 '8:00-9:00PM',
 '9:00-10:00PM',
 '10:00-11:00PM',
 '11:00-12:00AM'                         
]].mean().round(2)

In [18]:
df_mean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1586 entries, 202 to 9017050
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   12:00-1:00 AM  1586 non-null   float64
 1   1:00-2:00AM    1586 non-null   float64
 2   2:00-3:00AM    1586 non-null   float64
 3   3:00-4:00AM    1586 non-null   float64
 4   4:00-5:00AM    1586 non-null   float64
 5   5:00-6:00AM    1586 non-null   float64
 6   6:00-7:00AM    1586 non-null   float64
 7   7:00-8:00AM    1586 non-null   float64
 8   8:00-9:00AM    1586 non-null   float64
 9   9:00-10:00AM   1586 non-null   float64
 10  10:00-11:00AM  1586 non-null   float64
 11  11:00-12:00PM  1586 non-null   float64
 12  12:00-1:00PM   1586 non-null   float64
 13  1:00-2:00PM    1586 non-null   float64
 14  2:00-3:00PM    1586 non-null   float64
 15  3:00-4:00PM    1586 non-null   float64
 16  4:00-5:00PM    1586 non-null   float64
 17  5:00-6:00PM    1586 non-null   float64
 18  6:00-7:00PM    1586 non-null   float64
 19  7:00-8:00PM    1586 non-null   float64
 20  8:00-9:00PM    1586 non-null   float64
 21  9:00-10:00PM   1586 non-null   float64
 22  10:00-11:00PM  1586 non-null   float64
 23  11:00-12:00AM  1586 non-null   float64
dtypes: float64(24)
memory usage: 309.8 KB

In [19]:
geo_data.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 230558 entries, 0 to 230557
Columns: 122 entries, OBJECTID to geometry
dtypes: float64(7), geometry(1), int64(13), object(101)
memory usage: 214.6+ MB

In [144]:
df = pd.merge(df_mean, geo_data, left_on='Segment ID', right_on='SegmentID')

In [145]:
df.head()

,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,...,FromLeft,ToLeft,FromRight,ToRight,Join_ID,L_PD_Service_Area,R_PD_Service_Area,TRUCK_ROUTE_TYPE,Shape__Length,geometry
0,305.00,222.00,137.00,138.00,114.00,155.00,283.00,355.00,485.00,549.00,...,53,75,60,80,5297001000000,,,,395.059762,"LINESTRING (-74.24838 40.51448, -74.24756 40.5..."
1,61.72,35.83,19.39,17.39,26.39,54.00,118.00,217.28,246.22,218.33,...,322,398,321,399,5087601000000,,,2,837.363871,"LINESTRING (-74.21802 40.53225, -74.21807 40.5..."
2,61.39,39.28,20.56,13.44,20.61,47.94,119.00,255.33,241.67,225.56,...,410,438,411,439,5276601000000,,,2,261.608755,"LINESTRING (-74.20500 40.53651, -74.20532 40.5..."
3,57.11,37.67,21.72,17.72,26.67,60.56,148.72,291.94,262.61,227.44,...,611,633,608,636,5361001000000,,,2,258.118896,"LINESTRING (-74.19577 40.53985, -74.19543 40.5..."
4,84.83,52.50,36.50,33.33,64.67,152.72,236.78,319.94,384.17,376.22,...,1880,1916,1881,1913,5043001000000,,,2,283.598841,"LINESTRING (-74.20006 40.55659, -74.20018 40.5..."

In [2]:
df = pd.read_csv('../data/processed/traffic_count.csv')

In [5]:
df2 = df[[
    'geometry', 
    '12:00-1:00 AM',
    '1:00-2:00AM',
    '2:00-3:00AM',
    '3:00-4:00AM',
    '4:00-5:00AM',
    '5:00-6:00AM',
    '6:00-7:00AM',
    '7:00-8:00AM',
    '8:00-9:00AM',
    '9:00-10:00AM',
    '10:00-11:00AM',
    '11:00-12:00PM',
    '12:00-1:00PM',
    '1:00-2:00PM',
    '2:00-3:00PM',
    '3:00-4:00PM',
    '4:00-5:00PM',
    '5:00-6:00PM',
    '6:00-7:00PM',
    '7:00-8:00PM',
    '8:00-9:00PM',
    '9:00-10:00PM',
    '10:00-11:00PM',
    '11:00-12:00AM'
]]

from datetime import *
df2 = df2.rename(columns=lambda x: datetime.strftime(datetime.strptime(x.split('-')[0] + ' ' + x[-2:], '%I:%M %p'), "%H:%M") if x != 'geometry' else 'geometry')
df2

,geometry,00:00,01:00,02:00,03:00,04:00,05:00,06:00,07:00,08:00,...,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,11:00
0,LINESTRING (-74.24838489194531 40.514481854448...,305.00,222.00,137.00,138.00,114.00,155.00,283.00,355.00,485.00,...,665.00,649.00,671.00,700.00,658.00,646.00,707.00,620.00,540.00,504.00
1,LINESTRING (-74.2180154024865 40.5322453523612...,61.72,35.83,19.39,17.39,26.39,54.00,118.00,217.28,246.22,...,352.83,348.89,346.89,353.17,319.61,261.78,210.33,156.06,113.67,81.17
2,LINESTRING (-74.2049960190503 40.5365053262389...,61.39,39.28,20.56,13.44,20.61,47.94,119.00,255.33,241.67,...,351.17,348.06,351.11,340.33,337.39,274.89,211.61,160.28,112.06,88.94
3,"LINESTRING (-74.1957655801736 40.539846317408,...",57.11,37.67,21.72,17.72,26.67,60.56,148.72,291.94,262.61,...,393.78,401.39,370.61,389.17,363.39,305.50,245.28,178.89,125.28,85.72
4,LINESTRING (-74.2000610413353 40.5565861589871...,84.83,52.50,36.50,33.33,64.67,152.72,236.78,319.94,384.17,...,446.44,444.00,446.67,453.28,415.28,344.50,268.39,198.22,144.83,106.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752,LINESTRING (-73.8299730056643 40.7137902094127...,174.22,111.33,78.56,68.00,120.78,329.56,708.22,976.67,934.56,...,806.44,777.78,786.00,741.22,691.22,602.44,524.00,416.67,368.44,267.22
1753,"LINESTRING (-73.8298760986992 40.713949528989,...",260.78,166.89,125.33,103.89,113.89,148.89,259.67,554.22,823.67,...,1080.89,1470.67,1524.44,1441.33,1285.11,1213.89,875.22,610.89,455.33,367.78
1754,"LINESTRING (-73.8298760986992 40.713949528989,...",260.78,166.89,125.33,103.89,113.89,148.89,259.67,554.22,823.67,...,1080.89,1470.67,1524.44,1441.33,1285.11,1213.89,875.22,610.89,455.33,367.78
1755,"LINESTRING (-73.8298760986992 40.713949528989,...",260.78,166.89,125.33,103.89,113.89,148.89,259.67,554.22,823.67,...,1080.89,1470.67,1524.44,1441.33,1285.11,1213.89,875.22,610.89,455.33,367.78
1756,LINESTRING (-73.9665918483289 40.7941478827485...,359.89,273.67,215.33,176.56,187.33,273.22,446.33,653.00,702.67,...,745.22,759.33,787.00,802.44,789.89,696.22,605.33,546.67,530.89,451.67

In [6]:
df2.to_csv('../data/processed/traffic_count_2.csv', index=False)

In [7]:
df2.columns

Index(['geometry', '00:00', '01:00', '02:00', '03:00', '04:00', '05:00',
       '06:00', '07:00', '08:00', '09:00', '10:00', '23:00', '12:00', '13:00',
       '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00',
       '22:00', '11:00'],
      dtype='object')

In [111]:
df.apply(lambda x: x.split('-')[0] + x[:-2])

AttributeError: 'Series' object has no attribute 'split'

In [107]:
df['12:00-1:00 AM'] = pd.to_datetime('12:00-1:00 AM').strftime('%H:%M')

In [108]:
df.head()

,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,...,FromLeft,ToLeft,FromRight,ToRight,Join_ID,L_PD_Service_Area,R_PD_Service_Area,TRUCK_ROUTE_TYPE,Shape__Length,geometry
0,00:00,222.00,137.00,138.00,114.00,155.00,283.00,355.00,485.00,549.00,...,53,75,60,80,5297001000000,,,,395.059762,"LINESTRING (-74.24838 40.51448, -74.24756 40.5..."
1,00:00,35.83,19.39,17.39,26.39,54.00,118.00,217.28,246.22,218.33,...,322,398,321,399,5087601000000,,,2,837.363871,"LINESTRING (-74.21802 40.53225, -74.21807 40.5..."
2,00:00,39.28,20.56,13.44,20.61,47.94,119.00,255.33,241.67,225.56,...,410,438,411,439,5276601000000,,,2,261.608755,"LINESTRING (-74.20500 40.53651, -74.20532 40.5..."
3,00:00,37.67,21.72,17.72,26.67,60.56,148.72,291.94,262.61,227.44,...,611,633,608,636,5361001000000,,,2,258.118896,"LINESTRING (-74.19577 40.53985, -74.19543 40.5..."
4,00:00,52.50,36.50,33.33,64.67,152.72,236.78,319.94,384.17,376.22,...,1880,1916,1881,1913,5043001000000,,,2,283.598841,"LINESTRING (-74.20006 40.55659, -74.20018 40.5..."

In [99]:
df[['geometry', 
 '12:00-1:00 AM',
 '1:00-2:00AM',
 '2:00-3:00AM',
 '3:00-4:00AM',
 '4:00-5:00AM',
 '5:00-6:00AM',
 '6:00-7:00AM',
 '7:00-8:00AM',
 '8:00-9:00AM',
 '9:00-10:00AM',
 '10:00-11:00AM',
 '11:00-12:00PM',
 '12:00-1:00PM',
 '1:00-2:00PM',
 '2:00-3:00PM',
 '3:00-4:00PM',
 '4:00-5:00PM',
 '5:00-6:00PM',
 '6:00-7:00PM',
 '7:00-8:00PM',
 '8:00-9:00PM',
 '9:00-10:00PM',
 '10:00-11:00PM',
 '11:00-12:00AM']].to_csv('../data/processed/traffic_count.csv', index=False)